#服务器端口
server:
  port: 8102

#数据源配置
spring:
  datasource:
    url: "jdbc:mysql://119.3.163.11:3306/chatx?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8"
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
